name: Terraform CI/CD
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      apply:
        description: 'terraform apply'
        type: boolean
        default: false
      destroy:
        description: '-destroy'
        type: boolean
        default: false

defaults:
  run:
    working-directory: ./terraform/infra
env:
  TF_VAR_cloud_id: ${{ secrets.CLOUD_ID }}
  TF_VAR_folder_id: ${{ secrets.FOLDER_ID }}
  YC_KEY: ${{ secrets.YC_KEY }}
  AWS: ${{secrets.AWS }}
  SSH_PUB: ${{ secrets.SSH_PUB }}

jobs:
 terraform_apply:
   runs-on: ubuntu-22.04   
   defaults:
     run:
       working-directory: ./terraform/infra

   steps:
   - name: Checkout Code
     uses: actions/checkout@v4

   - name: Set up Terraform
     uses: hashicorp/setup-terraform@v3
     with:
       terraform_version: 1.8.4

   - name: Add keys and mirror
     run: |
        cat <<EOF > ~/.terraformrc
        provider_installation {
          network_mirror {
            url = "https://terraform-mirror.yandexcloud.net/"
            include = ["registry.terraform.io/*/*"]
          }
          direct {
            exclude = ["registry.terraform.io/*/*"]
          }
        }
        EOF
        echo "${YC_KEY}" > ./../S3_bucket_SA/.auth-key.json
        echo "${AWS}" > ./../S3_bucket_SA/.credentials
        mkdir ~/.ssh && echo "${SSH_PUB}" > ~/.ssh/yandxcld.pub

   - name: Terraform Init
     run: terraform init

   - name: Terraform Validate
     run: terraform validate

   - name: Terraform Plan
     if: github.event_name == 'push' || github.event.inputs.destroy == 'false'
     run: terraform plan -out=tfplan
     id: plan
     continue-on-error: true

   - name: Upload Plan Artifact
     if: github.event_name == 'push' || github.event.inputs.destroy == 'false'
     uses: actions/upload-artifact@v4
     with:
      name: tfplan
      path: terraform/infra/tfplan

   - name: Terraform Apply (auto)
     if: github.event_name == 'push' && github.ref_name == 'main'
     run: echo "Запуск (auto)" #terraform apply -auto-approve tfplan
    
   - name: Terraform Apply (manual)
     if: github.event_name == 'workflow_dispatch' && github.event.inputs.apply == 'true' && github.event.inputs.destroy == 'false'
     run: echo "Запуск (manual)" #terraform apply -auto-approve tfplan
    
   - name: Terraform Destroy (manual)
     if: github.event_name == 'workflow_dispatch' && github.event.inputs.apply == 'true' && github.event.inputs.destroy == 'true'
     run: echo "Удаление Destroy" #terraform destroy -auto-approve